baseURL: "https://utxo.cz/"
languageCode: "cs-cz"
theme: "hyde"
title: "UTXO.22"
params:
  disqusShortname: ""
  googleAnalytics: ""
  layoutReverse: false
  theme: "hyde"
  themeColor: ""
  description: |
    4.-5. Äerven 2022,  ğŸ‡¨ğŸ‡¿ Praha 
  description2: |
    OtevÅ™enÃ¡ komunitnÃ­ kryptomÄ›novÃ¡ konference
Menus:
  main:
    - Name: "Dokumentace"
      URL: "https://docs.utxo.cz"
    - Name: "Discord"
      URL: "https://discord.gg/hKuqyYPcxQ"
